# Generated by Django 3.0.2 on 2020-01-31 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200131_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='genre',
        ),
    ]
