# Generated by Django 3.0.2 on 2020-01-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
