# Generated by Django 3.0.2 on 2020-02-02 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_suscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suscribe',
            old_name='suscribe_id',
            new_name='email_id',
        ),
    ]
