# Generated by Django 3.0.2 on 2020-02-02 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200202_1034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suscribe',
            new_name='Suscribption',
        ),
    ]
